name: fanchat
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+6

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fcm_config: ^3.3.7
  equatable: ^2.0.5
  flutter_stripe: ^6.0.0
  localization: ^2.1.0
  cupertino_icons: ^1.0.2
  splash_screen_view: ^3.0.0
  hexcolor: ^2.0.6
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.15
  carousel_slider: ^4.1.1
  flutter_speed_dial: ^6.0.0
  image_picker: ^0.8.4+8
  video_player:
  country_pickers: ^2.0.0
  intl:
  conditional_builder_null_safety: ^0.0.6
  #email_auth:
  lottie: ^1.4.1
  provider:
  pinput: ^2.2.11
  easy_container: ^1.0.4
  intl_phone_field: ^3.1.0
  change_app_package_name: ^1.1.0
  flutter_local_notifications: ^9.7.0
  #chewie: ^1.3.5
  flutter_native_timezone: ^2.0.0
  custom_clippers: ^1.0.0
  overlay_support: ^2.0.1
  url_launcher: ^6.1.5
  flutter_paypal:
  searchable_listview: ^2.0.1
  timer_builder: ^2.0.0
  circular_countdown_timer: ^0.2.2
  pay: ^1.0.11
#  stripe_payment: ^1.1.4
#  flutter_credit_card: ^3.0.2


  #Google SignIn
  #google_sign_in: ^5.4.1
 # flutter_login_facebook:
  #FaceBook SignIn
  #flutter_facebook_auth: ^3.5.0
  #Firebase
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.1
  cloud_firestore: ^3.4.2
  firebase_storage:
  modal_bottom_sheet: ^2.1.2
  firebase_messaging: ^11.2.5
  firebase_phone_auth_handler:
  webview_flutter: ^2.1.1
  get:
  http: ^0.13.3
  http_auth: ^1.0.1
 #BLOC
  flutter_bloc:
  bloc:
  dio: ^4.0.4
  flutter_svg:
#sqlFlite
  #sqflite: ^2.0.3+1
  #///////////////////////////////// audio players:
  permission_handler: ^8.3.0
#  record_mp3: ^3.0.0
  path_provider: ^2.0.8
  uuid: ^3.0.5
  voice_message_package: ^0.0.74
  cached_network_image: ^3.2.1
  flutter_cache_manager: ^3.3.0
  cached_video_player:
  media_cache_manager: ^0.0.2+1
  fijkplayer: ^0.10.1
  video_thumbnail: ^0.5.3
  flutter_blurhash: ^0.7.0
  video_thumbnail_imageview: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/default_payment_profile_google_pay.json
    - assets/json/default_payment_profile_apple_pay.json

  fonts:
    - family: fan
      fonts:
        - asset: assets/fonts/fanfont.ttf
          weight: 700
    - family: Roboto Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
